deps.fabric_api=0.145.6+26.2
deps.modmenu=18.0.0-alpha.8
deps.disable_modmenu=true

# Minecraft dependency for fabric.mod.json
mod.mc_dep=>=26.2-alpha.3

# Release title for Modrinth and Curseforge
mod.mc_title=26.2-snapshot-3

# Space-separated compatible versions for publishing
mod.mc_targets=26.2-snapshot-3